package com.example.pokedex

import android.content.Intent
import android.graphics.Bitmap
import android.os.Bundle
import android.view.*
import androidx.fragment.app.Fragment
import android.widget.AdapterView
import android.widget.LinearLayout
import androidx.navigation.findNavController
import androidx.navigation.ui.NavigationUI
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.example.pokedex.Activity.DetailActivity

// TODO: Rename parameter arguments, choose names that match
// the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
private const val ARG_PARAM1 = "param1"
private const val ARG_PARAM2 = "param2"

/**
 * A simple [Fragment] subclass.
 * Use the [PokemonList.newInstance] factory method to
 * create an instance of this fragment.
 */
class PokemonList : Fragment(), CustomRecyclerAdapter.OnItemClickListener {
    private var param1: String? = null
    private var param2: String? = null

    private lateinit var recyclerVw: RecyclerView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        arguments?.let {
            param1 = it.getString(ARG_PARAM1)
            param2 = it.getString(ARG_PARAM2)

        }
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflates the layout for this fragment
        val view: View= inflater.inflate(R.layout.fragment_pokemon_list, container, false)


        recyclerVw = view.findViewById(R.id.recyclerView)
        val customAdapter = CustomRecyclerAdapter(pokeTestList, this)
        recyclerVw.adapter = customAdapter
        recyclerVw.layoutManager = LinearLayoutManager(context)
        recyclerVw.setHasFixedSize(true)


        setHasOptionsMenu(true)
        return view
    }

    override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
        super.onCreateOptionsMenu(menu,inflater)
        inflater.inflate(R.menu.searchmenu, menu)

    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean { // Navigates to search fragment on clicking menu item
        return NavigationUI.onNavDestinationSelected(
            item,
            requireView().findNavController())
                || super.onOptionsItemSelected(item)
    }

    override fun onItemClick(position: Int) {
        //Creates an Intent object by giving the context and the class of next activity to be opened
        // A passive data structure holding an abstract description of an action to be performed.
        val clickedItem: ReworkedPokemonItem = pokeTestList[position]
        val mIntent: Intent? = Intent(this.context, DetailActivity::class.java)
        mIntent?.putExtra("pokemonSprite", clickedItem.pokemonSprite) //Attach the key value pair using putExtra to this intent
        mIntent?.putExtra("pokemonType", clickedItem.pokemonType1)
        mIntent?.putExtra("pokemonType2", clickedItem.pokemonType2)
        mIntent?.putExtra("pokemonName", clickedItem.pokemonName)

        startActivity(mIntent)
}
    companion object {
        /**
         * Use this factory method to create a new instance of
         * this fragment using the provided parameters.
         *
         * @param param1 Parameter 1.
         * @param param2 Parameter 2.
         * @return A new instance of fragment pokemonList.
         */
        // TODO: Rename and change types and number of parameters
        @JvmStatic
        fun newInstance(param1: String, param2: String) =
            PokemonList().apply {
                arguments = Bundle().apply {
                    putString(ARG_PARAM1, param1)
                    putString(ARG_PARAM2, param2)
                }
            }
    }
}
// List of all pokemon
val allPokemon = listOf("bulbasaur ",
    "ivysaur ",
    "venusaur ",
    "charmander ",
    "charmeleon ",
    "charizard ",
    "squirtle ",
    "wartortle ",
    "blastoise ",
    "caterpie ",
    "metapod ",
    "butterfree ",
    "weedle ",
    "kakuna ",
    "beedrill ",
    "pidgey ",
    "pidgeotto ",
    "pidgeot ",
    "rattata ",
    "raticate ",
    "spearow ",
    "fearow ",
    "ekans ",
    "arbok ",
    "pikachu ",
    "raichu ",
    "sandshrew ",
    "sandslash ",
    "nidorina ",
    "nidoqueen ",
    "nidorino ",
    "nidoking ",
    "clefairy ",
    "clefable ",
    "vulpix ",
    "ninetales ",
    "jigglypuff ",
    "wigglytuff ",
    "zubat ",
    "golbat ",
    "oddish ",
    "gloom ",
    "vileplume ",
    "paras ",
    "parasect ",
    "venonat ",
    "venomoth ",
    "diglett ",
    "dugtrio ",
    "meowth ",
    "persian ",
    "psyduck ",
    "golduck ",
    "mankey ",
    "primeape ",
    "growlithe ",
    "arcanine ",
    "poliwag ",
    "poliwhirl ",
    "poliwrath ",
    "abra ",
    "kadabra ",
    "alakazam ",
    "machop ",
    "machoke ",
    "machamp ",
    "bellsprout ",
    "weepinbell ",
    "victreebel ",
    "tentacool ",
    "tentacruel ",
    "geodude ",
    "graveler ",
    "golem ",
    "ponyta ",
    "rapidash ",
    "slowpoke ",
    "slowbro ",
    "magnemite ",
    "magneton ",
    "farfetch'd ",
    "farfetchd",
    "doduo ",
    "dodrio ",
    "seel ",
    "dewgong ",
    "grimer ",
    "muk ",
    "shellder ",
    "cloyster ",
    "gastly ",
    "haunter ",
    "gengar ",
    "onix ",
    "drowzee ",
    "hypno ",
    "krabby ",
    "kingler ",
    "voltorb ",
    "electrode ",
    "exeggcute ",
    "exeggutor ",
    "cubone ",
    "marowak ",
    "hitmonlee ",
    "hitmonchan ",
    "lickitung ",
    "koffing ",
    "weezing ",
    "rhyhorn ",
    "rhydon ",
    "chansey ",
    "tangela ",
    "kangaskhan ",
    "horsea ",
    "seadra ",
    "goldeen ",
    "seaking ",
    "staryu ",
    "starmie ",
    "mr. mime ",
    "mr mime ",
    "scyther ",
    "jynx ",
    "electabuzz ",
    "magmar ",
    "pinsir ",
    "tauros ",
    "magikarp ",
    "gyarados ",
    "lapras ",
    "ditto ",
    "eevee ",
    "vaporeon ",
    "jolteon ",
    "flareon ",
    "porygon ",
    "omanyte ",
    "omastar ",
    "kabuto ",
    "kabutops ",
    "aerodactyl ",
    "snorlax ",
    "articuno ",
    "zapdos ",
    "moltres ",
    "dratini ",
    "dragonair ",
    "dragonite ",
    "mewtwo ",
    "mew ",
    "chikorita ",
    "bayleef ",
    "meganium ",
    "cyndaquil ",
    "quilava ",
    "typhlosion ",
    "totodile ",
    "croconaw ",
    "feraligatr ",
    "sentret ",
    "furret ",
    "hoothoot ",
    "noctowl ",
    "ledyba ",
    "ledian ",
    "spinarak ",
    "ariados ",
    "crobat ",
    "chinchou ",
    "lanturn ",
    "pichu ",
    "cleffa ",
    "igglybuff ",
    "togepi ",
    "togetic ",
    "natu ",
    "xatu ",
    "mareep ",
    "flaaffy ",
    "ampharos ",
    "bellossom ",
    "marill ",
    "azumarill ",
    "sudowoodo ",
    "politoed ",
    "hoppip ",
    "skiploom ",
    "jumpluff ",
    "aipom ",
    "sunkern ",
    "sunflora ",
    "yanma ",
    "wooper ",
    "quagsire ",
    "espeon ",
    "umbreon ",
    "murkrow ",
    "slowking ",
    "misdreavus ",
    "unown ",
    "wobbuffet ",
    "girafarig ",
    "pineco ",
    "forretress ",
    "dunsparce ",
    "gligar ",
    "steelix ",
    "snubbull ",
    "granbull ",
    "qwilfish ",
    "scizor ",
    "shuckle ",
    "heracross ",
    "sneasel ",
    "teddiursa ",
    "ursaring ",
    "slugma ",
    "magcargo ",
    "swinub ",
    "piloswine ",
    "corsola ",
    "remoraid ",
    "octillery ",
    "delibird ",
    "mantine ",
    "skarmory ",
    "houndour ",
    "houndoom ",
    "kingdra ",
    "phanpy ",
    "donphan ",
    "porygon2 ",
    "stantler ",
    "smeargle ",
    "tyrogue ",
    "hitmontop ",
    "smoochum ",
    "elekid ",
    "magby ",
    "miltank ",
    "blissey ",
    "raikou ",
    "entei ",
    "suicune ",
    "larvitar ",
    "pupitar ",
    "tyranitar ",
    "lugia ",
    "ho-oh ",
    "celebi ",
    "treecko ",
    "grovyle ",
    "sceptile ",
    "torchic ",
    "combusken ",
    "blaziken ",
    "mudkip ",
    "marshtomp ",
    "swampert ",
    "poochyena ",
    "mightyena ",
    "zigzagoon ",
    "linoone ",
    "wurmple ",
    "silcoon ",
    "beautifly ",
    "cascoon ",
    "dustox ",
    "lotad ",
    "lombre ",
    "ludicolo ",
    "seedot ",
    "nuzleaf ",
    "shiftry ",
    "taillow ",
    "swellow ",
    "wingull ",
    "pelipper ",
    "ralts ",
    "kirlia ",
    "gardevoir ",
    "surskit ",
    "masquerain ",
    "shroomish ",
    "breloom ",
    "slakoth ",
    "vigoroth ",
    "slaking ",
    "nincada ",
    "ninjask ",
    "shedinja ",
    "whismur ",
    "loudred ",
    "exploud ",
    "makuhita ",
    "hariyama ",
    "azurill ",
    "nosepass ",
    "skitty ",
    "delcatty ",
    "sableye ",
    "mawile ",
    "aron ",
    "lairon ",
    "aggron ",
    "meditite ",
    "medicham ",
    "electrike ",
    "manectric ",
    "plusle ",
    "minun ",
    "volbeat ",
    "illumise ",
    "roselia ",
    "gulpin ",
    "swalot ",
    "carvanha ",
    "sharpedo ",
    "wailmer ",
    "wailord ",
    "numel ",
    "camerupt ",
    "torkoal ",
    "spoink ",
    "grumpig ",
    "spinda ",
    "trapinch ",
    "vibrava ",
    "flygon ",
    "cacnea ",
    "cacturne ",
    "swablu ",
    "altaria ",
    "zangoose ",
    "seviper ",
    "lunatone ",
    "solrock ",
    "barboach ",
    "whiscash ",
    "corphish ",
    "crawdaunt ",
    "baltoy ",
    "claydol ",
    "lileep ",
    "cradily ",
    "anorith ",
    "armaldo ",
    "feebas ",
    "milotic ",
    "castform ",
    "kecleon ",
    "shuppet ",
    "banette ",
    "duskull ",
    "dusclops ",
    "tropius ",
    "chimecho ",
    "absol ",
    "wynaut ",
    "snorunt ",
    "glalie ",
    "spheal ",
    "sealeo ",
    "walrein ",
    "clamperl ",
    "huntail ",
    "gorebyss ",
    "relicanth ",
    "luvdisc ",
    "bagon ",
    "shelgon ",
    "salamence ",
    "beldum ",
    "metang ",
    "metagross ",
    "regirock ",
    "regice ",
    "registeel ",
    "latias ",
    "latios ",
    "kyogre ",
    "groudon ",
    "rayquaza ",
    "jirachi ",
    "deoxys ",
    "turtwig ",
    "grotle ",
    "torterra ",
    "chimchar ",
    "monferno ",
    "infernape ",
    "piplup ",
    "prinplup ",
    "empoleon ",
    "starly ",
    "staravia ",
    "staraptor ",
    "bidoof ",
    "bibarel ",
    "kricketot ",
    "kricketune ",
    "shinx ",
    "luxio ",
    "luxray ",
    "budew ",
    "roserade ",
    "cranidos ",
    "rampardos ",
    "shieldon ",
    "bastiodon ",
    "burmy ",
    "wormadam ",
    "mothim ",
    "combee ",
    "vespiquen ",
    "pachirisu ",
    "buizel ",
    "floatzel ",
    "cherubi ",
    "cherrim ",
    "shellos ",
    "gastrodon ",
    "ambipom ",
    "drifloon ",
    "drifblim ",
    "buneary ",
    "lopunny ",
    "mismagius ",
    "honchkrow ",
    "glameow ",
    "purugly ",
    "chingling ",
    "stunky ",
    "skuntank ",
    "bronzor ",
    "bronzong ",
    "bonsly ",
    "mime jr. ",
    "happiny ",
    "chatot ",
    "spiritomb ",
    "gible ",
    "gabite ",
    "garchomp ",
    "munchlax ",
    "riolu ",
    "lucario ",
    "hippopotas ",
    "hippowdon ",
    "skorupi ",
    "drapion ",
    "croagunk ",
    "toxicroak ",
    "carnivine ",
    "finneon ",
    "lumineon ",
    "mantyke ",
    "snover ",
    "abomasnow ",
    "weavile ",
    "magnezone ",
    "lickilicky ",
    "rhyperior ",
    "tangrowth ",
    "electivire ",
    "magmortar ",
    "togekiss ",
    "yanmega ",
    "leafeon ",
    "glaceon ",
    "gliscor ",
    "mamoswine ",
    "porygon-z ",
    "gallade ",
    "probopass ",
    "dusknoir ",
    "froslass ",
    "rotom ",
    "uxie ",
    "mesprit ",
    "azelf ",
    "dialga ",
    "palkia ",
    "heatran ",
    "regigigas ",
    "giratina ",
    "cresselia ",
    "phione ",
    "manaphy ",
    "darkrai ",
    "shaymin ",
    "arceus ",
    "victini ",
    "snivy ",
    "servine ",
    "serperior ",
    "tepig ",
    "pignite ",
    "emboar ",
    "oshawott ",
    "dewott ",
    "samurott ",
    "patrat ",
    "watchog ",
    "lillipup ",
    "herdier ",
    "stoutland ",
    "purrloin ",
    "liepard ",
    "pansage ",
    "simisage ",
    "pansear ",
    "simisear ",
    "panpour ",
    "simipour ",
    "munna ",
    "musharna ",
    "pidove ",
    "tranquill ",
    "unfezant ",
    "blitzle ",
    "zebstrika ",
    "roggenrola ",
    "boldore ",
    "gigalith ",
    "woobat ",
    "swoobat ",
    "drilbur ",
    "excadrill ",
    "audino ",
    "timburr ",
    "gurdurr ",
    "conkeldurr ",
    "tympole ",
    "palpitoad ",
    "seismitoad ",
    "throh ",
    "sawk ",
    "sewaddle ",
    "swadloon ",
    "leavanny ",
    "venipede ",
    "whirlipede ",
    "scolipede ",
    "cottonee ",
    "whimsicott ",
    "petilil ",
    "lilligant ",
    "basculin ",
    "sandile ",
    "krokorok ",
    "krookodile ",
    "darumaka ",
    "darmanitan ",
    "maractus ",
    "dwebble ",
    "crustle ",
    "scraggy ",
    "scrafty ",
    "sigilyph ",
    "yamask ",
    "cofagrigus ",
    "tirtouga ",
    "carracosta ",
    "archen ",
    "archeops ",
    "trubbish ",
    "garbodor ",
    "zorua ",
    "zoroark ",
    "minccino ",
    "cinccino ",
    "gothita ",
    "gothorita ",
    "gothitelle ",
    "solosis ",
    "duosion ",
    "reuniclus ",
    "ducklett ",
    "swanna ",
    "vanillite ",
    "vanillish ",
    "vanilluxe ",
    "deerling ",
    "sawsbuck ",
    "emolga ",
    "karrablast ",
    "escavalier ",
    "foongus ",
    "amoonguss ",
    "frillish ",
    "jellicent ",
    "alomomola ",
    "joltik ",
    "galvantula ",
    "ferroseed ",
    "ferrothorn ",
    "klink ",
    "klang ",
    "klinklang ",
    "tynamo ",
    "eelektrik ",
    "eelektross ",
    "elgyem ",
    "beheeyem ",
    "litwick ",
    "lampent ",
    "chandelure ",
    "axew ",
    "fraxure ",
    "haxorus ",
    "cubchoo ",
    "beartic ",
    "cryogonal ",
    "shelmet ",
    "accelgor ",
    "stunfisk ",
    "mienfoo ",
    "mienshao ",
    "druddigon ",
    "golett ",
    "golurk ",
    "pawniard ",
    "bisharp ",
    "bouffalant ",
    "rufflet ",
    "braviary ",
    "vullaby ",
    "mandibuzz ",
    "heatmor ",
    "durant ",
    "deino ",
    "zweilous ",
    "hydreigon ",
    "larvesta ",
    "volcarona ",
    "cobalion ",
    "terrakion ",
    "virizion ",
    "tornadus ",
    "thundurus ",
    "reshiram ",
    "zekrom ",
    "landorus ",
    "kyurem ",
    "keldeo ",
    "meloetta ",
    "genesect ",
    "chespin ",
    "quilladin ",
    "chesnaught ",
    "fennekin ",
    "braixen ",
    "delphox ",
    "froakie ",
    "frogadier ",
    "greninja ",
    "bunnelby ",
    "diggersby ",
    "fletchling ",
    "fletchinder ",
    "talonflame ",
    "scatterbug ",
    "spewpa ",
    "vivillon ",
    "litleo ",
    "pyroar ",
    "flabébé ",
    "floette ",
    "florges ",
    "skiddo ",
    "gogoat ",
    "pancham ",
    "pangoro ",
    "furfrou ",
    "espurr ",
    "meowstic ",
    "honedge ",
    "doublade ",
    "aegislash ",
    "spritzee ",
    "aromatisse ",
    "swirlix ",
    "slurpuff ",
    "inkay ",
    "malamar ",
    "binacle ",
    "barbaracle ",
    "skrelp ",
    "dragalge ",
    "clauncher ",
    "clawitzer ",
    "helioptile ",
    "heliolisk ",
    "tyrunt ",
    "tyrantrum ",
    "amaura ",
    "aurorus ",
    "sylveon ",
    "hawlucha ",
    "dedenne ",
    "carbink ",
    "goomy ",
    "sliggoo ",
    "goodra ",
    "klefki ",
    "phantump ",
    "trevenant ",
    "pumpkaboo ",
    "gourgeist ",
    "bergmite ",
    "avalugg ",
    "noibat ",
    "noivern ",
    "xerneas ",
    "yveltal ",
    "zygarde ",
    "diancie ",
    "hoopa ",
    "volcanion ",
    "rowlet ",
    "dartrix ",
    "decidueye ",
    "litten ",
    "torracat ",
    "incineroar ",
    "popplio ",
    "brionne ",
    "primarina ",
    "pikipek ",
    "trumbeak ",
    "toucannon ",
    "yungoos ",
    "gumshoos ",
    "grubbin ",
    "charjabug ",
    "vikavolt ",
    "crabrawler ",
    "crabominable ",
    "oricorio ",
    "cutiefly ",
    "ribombee ",
    "rockruff ",
    "lycanroc ",
    "wishiwashi ",
    "mareanie ",
    "toxapex ",
    "mudbray ",
    "mudsdale ",
    "dewpider ",
    "araquanid ",
    "fomantis ",
    "lurantis ",
    "morelull ",
    "shiinotic ",
    "salandit ",
    "salazzle ",
    "stufful ",
    "bewear ",
    "bounsweet ",
    "steenee ",
    "tsareena ",
    "comfey ",
    "oranguru ",
    "passimian ",
    "wimpod ",
    "golisopod ",
    "sandygast ",
    "palossand ",
    "pyukumuku ",
    "type: null ",
    "silvally ",
    "minior ",
    "komala ",
    "turtonator ",
    "togedemaru ",
    "mimikyu ",
    "bruxish ",
    "drampa ",
    "dhelmise ",
    "jangmo-o ",
    "hakamo-o ",
    "kommo-o ",
    "tapu koko ",
    "tapu lele ",
    "tapu bulu ",
    "tapu fini ",
    "cosmog ",
    "cosmoem ",
    "solgaleo ",
    "lunala ",
    "nihilego ",
    "buzzwole ",
    "pheromosa ",
    "xurkitree ",
    "celesteela ",
    "kartana ",
    "guzzlord ",
    "necrozma ",
    "magearna ",
    "marshadow ",
    "poipole ",
    "naganadel ",
    "stakataka ",
    "blacephalon ",
    "zeraora "

)



